# Generated by Django 4.2.7 on 2023-11-14 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('m', '男'), ('f', '女')], default='m', max_length=10, verbose_name='性别')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('info', models.CharField(help_text='一句话介绍自己', max_length=255, verbose_name='个人简介')),
                ('grade', models.CharField(max_length=4, verbose_name='年级')),
                ('number', models.CharField(max_length=6, verbose_name='编号')),
                ('password', models.CharField(max_length=30, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('gender', models.CharField(choices=[('m', '男'), ('f', '女')], default='m', max_length=10, verbose_name='性别')),
                ('birthday', models.DateField(verbose_name='生日')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('info', models.CharField(help_text='一句话介绍自己', max_length=255, verbose_name='个人简介')),
                ('grade', models.CharField(max_length=4, verbose_name='年级')),
                ('number', models.CharField(max_length=6, verbose_name='学号')),
                ('password', models.CharField(max_length=30, verbose_name='密码')),
            ],
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('grade', 'number'), name='student_id'),
        ),
        migrations.AddConstraint(
            model_name='administrator',
            constraint=models.UniqueConstraint(fields=('grade', 'number'), name='administrator_id'),
        ),
    ]
